export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SYSTEM_ERROR = "AUTH_SYSTEM_ERROR";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";

export const ADD_TRANSAKSI_SUCCESS = "ADD_TRANSAKSI_SUCCESS";
export const ADD_TRANSAKSI_LOADING = "ADD_TRANSAKSI_LOADING";
export const ADD_TRANSAKSI_ERROR = "ADD_TRANSAKSI_ERROR";

export const GET_CHART_SUCCESS = "GET_CHART_SUCCESS";
export const GET_CHART_LOADING = "GET_CHART_LOADING";
export const GET_CHART_ERROR = "GET_CHART_ERROR";

export const DELETE_CHART_SUCCESS = "DELETE_CHART_SUCCESS";
export const DELETE_CHART_LOADING = "DELETE_CHART_LOADING";
export const DELETE_CHART_ERROR = "DELETE_CHART_ERROR";
