export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SYSTEM_ERROR = "AUTH_SYSTEM_ERROR";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";
